//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPagStone.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TransactionErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransactionErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppPagStone.Resources.TransactionErrors", typeof(TransactionErrors).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não aprovado.
        /// </summary>
        internal static string c1000 {
            get {
                return ResourceManager.GetString("c1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão vencido.
        /// </summary>
        internal static string c1001 {
            get {
                return ResourceManager.GetString("c1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspeita de fraude.
        /// </summary>
        internal static string c1002 {
            get {
                return ResourceManager.GetString("c1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estabelecimento entrar em contato com emissor.
        /// </summary>
        internal static string c1003 {
            get {
                return ResourceManager.GetString("c1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão com restrição.
        /// </summary>
        internal static string c1004 {
            get {
                return ResourceManager.GetString("c1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estabelecimento entrar em contato com departamento de segurança do adquirente.
        /// </summary>
        internal static string c1005 {
            get {
                return ResourceManager.GetString("c1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentativas de senha excedidas.
        /// </summary>
        internal static string c1006 {
            get {
                return ResourceManager.GetString("c1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar o emissor.
        /// </summary>
        internal static string c1007 {
            get {
                return ResourceManager.GetString("c1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar as condições especiais do emissor.
        /// </summary>
        internal static string c1008 {
            get {
                return ResourceManager.GetString("c1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estabelecimento inválido.
        /// </summary>
        internal static string c1009 {
            get {
                return ResourceManager.GetString("c1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor inválido.
        /// </summary>
        internal static string c1010 {
            get {
                return ResourceManager.GetString("c1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid card number.
        /// </summary>
        internal static string c1011 {
            get {
                return ResourceManager.GetString("c1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha necessária.
        /// </summary>
        internal static string c1012 {
            get {
                return ResourceManager.GetString("c1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma conta do tipo selecionado.
        /// </summary>
        internal static string c1014 {
            get {
                return ResourceManager.GetString("c1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função selecionada não suportada.
        /// </summary>
        internal static string c1015 {
            get {
                return ResourceManager.GetString("c1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo insuficiente.
        /// </summary>
        internal static string c1016 {
            get {
                return ResourceManager.GetString("c1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida.
        /// </summary>
        internal static string c1017 {
            get {
                return ResourceManager.GetString("c1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transação não permitida para o portador.
        /// </summary>
        internal static string c1019 {
            get {
                return ResourceManager.GetString("c1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transação não permitida para o terminal.
        /// </summary>
        internal static string c1020 {
            get {
                return ResourceManager.GetString("c1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite de valor para saque excedido.
        /// </summary>
        internal static string c1021 {
            get {
                return ResourceManager.GetString("c1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violação de segurança.
        /// </summary>
        internal static string c1022 {
            get {
                return ResourceManager.GetString("c1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite de quantidade de saques excedido.
        /// </summary>
        internal static string c1023 {
            get {
                return ResourceManager.GetString("c1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violação da lei.
        /// </summary>
        internal static string c1024 {
            get {
                return ResourceManager.GetString("c1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão bloqueado.
        /// </summary>
        internal static string c1025 {
            get {
                return ResourceManager.GetString("c1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de senha inválidos.
        /// </summary>
        internal static string c1026 {
            get {
                return ResourceManager.GetString("c1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro no tamanho da senha.
        /// </summary>
        internal static string c1027 {
            get {
                return ResourceManager.GetString("c1027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro de sincronia de chave de senha.
        /// </summary>
        internal static string c1028 {
            get {
                return ResourceManager.GetString("c1028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspeita de cartão falso.
        /// </summary>
        internal static string c1029 {
            get {
                return ResourceManager.GetString("c1029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeda inaceitável para o emissor.
        /// </summary>
        internal static string c1030 {
            get {
                return ResourceManager.GetString("c1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão perdido ou roubado.
        /// </summary>
        internal static string c1032 {
            get {
                return ResourceManager.GetString("c1032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta encerrada.
        /// </summary>
        internal static string c1035 {
            get {
                return ResourceManager.GetString("c1035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta poupança encerrada ou bloqueada para encerramento.
        /// </summary>
        internal static string c1036 {
            get {
                return ResourceManager.GetString("c1036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta de crédito encerrada ou bloqueada para encerramento.
        /// </summary>
        internal static string c1037 {
            get {
                return ResourceManager.GetString("c1037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta corrente encerrada ou bloquada para encerramento.
        /// </summary>
        internal static string c1039 {
            get {
                return ResourceManager.GetString("c1039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status ruim para conta de origem.
        /// </summary>
        internal static string c1041 {
            get {
                return ResourceManager.GetString("c1041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status ruim para conta de destino.
        /// </summary>
        internal static string c1042 {
            get {
                return ResourceManager.GetString("c1042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de segurança inválido.
        /// </summary>
        internal static string c1045 {
            get {
                return ResourceManager.GetString("c1045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troca de senha necessária.
        /// </summary>
        internal static string c1047 {
            get {
                return ResourceManager.GetString("c1047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova senha inválida.
        /// </summary>
        internal static string c1048 {
            get {
                return ResourceManager.GetString("c1048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de pagamento inválida.
        /// </summary>
        internal static string c1057 {
            get {
                return ResourceManager.GetString("c1057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transação não completou normalmente no terminal.
        /// </summary>
        internal static string c1060 {
            get {
                return ResourceManager.GetString("c1060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transação não suportada pelo emissor.
        /// </summary>
        internal static string c1061 {
            get {
                return ResourceManager.GetString("c1061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saque fácil não disponível.
        /// </summary>
        internal static string c1062 {
            get {
                return ResourceManager.GetString("c1062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite de saque fácil excedido.
        /// </summary>
        internal static string c1063 {
            get {
                return ResourceManager.GetString("c1063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negado offline pelo terminal.
        /// </summary>
        internal static string c1064 {
            get {
                return ResourceManager.GetString("c1064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negado, não foi possível processar offline.
        /// </summary>
        internal static string c1065 {
            get {
                return ResourceManager.GetString("c1065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não aprovado.
        /// </summary>
        internal static string c2000 {
            get {
                return ResourceManager.GetString("c2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão vencido.
        /// </summary>
        internal static string c2001 {
            get {
                return ResourceManager.GetString("c2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspeita de fraude.
        /// </summary>
        internal static string c2002 {
            get {
                return ResourceManager.GetString("c2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estabelecimento entrar em contato com emissor.
        /// </summary>
        internal static string c2003 {
            get {
                return ResourceManager.GetString("c2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão com restrição.
        /// </summary>
        internal static string c2004 {
            get {
                return ResourceManager.GetString("c2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estabelecimento entrar em contato com departamento de segurança do adquirente.
        /// </summary>
        internal static string c2005 {
            get {
                return ResourceManager.GetString("c2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentativas de senha excedidas.
        /// </summary>
        internal static string c2006 {
            get {
                return ResourceManager.GetString("c2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condições especiais.
        /// </summary>
        internal static string c2007 {
            get {
                return ResourceManager.GetString("c2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão perdido.
        /// </summary>
        internal static string c2008 {
            get {
                return ResourceManager.GetString("c2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão roubado.
        /// </summary>
        internal static string c2009 {
            get {
                return ResourceManager.GetString("c2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspeita de cartão falso.
        /// </summary>
        internal static string c2010 {
            get {
                return ResourceManager.GetString("c2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite de quantidade de saques excedido.
        /// </summary>
        internal static string c2011 {
            get {
                return ResourceManager.GetString("c2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite de valor para saque excedido.
        /// </summary>
        internal static string c2012 {
            get {
                return ResourceManager.GetString("c2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algum campo obrigatório não foi enviado ou foi enviado de maneira incorreta.
        /// </summary>
        internal static string c400 {
            get {
                return ResourceManager.GetString("c400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro no formato da mensagem.
        /// </summary>
        internal static string c9100 {
            get {
                return ResourceManager.GetString("c9100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transação inválida.
        /// </summary>
        internal static string c9102 {
            get {
                return ResourceManager.GetString("c9102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tente novamente.
        /// </summary>
        internal static string c9103 {
            get {
                return ResourceManager.GetString("c9103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adquirente não suportado pelo switch.
        /// </summary>
        internal static string c9105 {
            get {
                return ResourceManager.GetString("c9105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emissor fora de operação.
        /// </summary>
        internal static string c9107 {
            get {
                return ResourceManager.GetString("c9107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível enviar a transação para o destinatário.
        /// </summary>
        internal static string c9108 {
            get {
                return ResourceManager.GetString("c9108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro no sistema.
        /// </summary>
        internal static string c9109 {
            get {
                return ResourceManager.GetString("c9109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emissor se desconectou.
        /// </summary>
        internal static string c9110 {
            get {
                return ResourceManager.GetString("c9110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emissor não respondeu em tempo.
        /// </summary>
        internal static string c9111 {
            get {
                return ResourceManager.GetString("c9111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emissor indisponível.
        /// </summary>
        internal static string c9112 {
            get {
                return ResourceManager.GetString("c9112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmissão duplicada.
        /// </summary>
        internal static string c9113 {
            get {
                return ResourceManager.GetString("c9113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar a transação original.
        /// </summary>
        internal static string c9114 {
            get {
                return ResourceManager.GetString("c9114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC incorreto.
        /// </summary>
        internal static string c9116 {
            get {
                return ResourceManager.GetString("c9116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro de sincronização de chave de MAC.
        /// </summary>
        internal static string c9117 {
            get {
                return ResourceManager.GetString("c9117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma chave de comunicação disponível.
        /// </summary>
        internal static string c9118 {
            get {
                return ResourceManager.GetString("c9118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro de sincronização de chave de encriptação.
        /// </summary>
        internal static string c9119 {
            get {
                return ResourceManager.GetString("c9119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro de segurança de software/hardware, tente novamente.
        /// </summary>
        internal static string c9120 {
            get {
                return ResourceManager.GetString("c9120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro de segurança de software/hardware.
        /// </summary>
        internal static string c9121 {
            get {
                return ResourceManager.GetString("c9121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número da mensagem fora de sequência.
        /// </summary>
        internal static string c9122 {
            get {
                return ResourceManager.GetString("c9122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisição em progresso.
        /// </summary>
        internal static string c9123 {
            get {
                return ResourceManager.GetString("c9123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de segurança inválido.
        /// </summary>
        internal static string c9124 {
            get {
                return ResourceManager.GetString("c9124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro no banco de dados.
        /// </summary>
        internal static string c9125 {
            get {
                return ResourceManager.GetString("c9125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro nos dados de recorrência.
        /// </summary>
        internal static string c9132 {
            get {
                return ResourceManager.GetString("c9132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização não permitida.
        /// </summary>
        internal static string c9133 {
            get {
                return ResourceManager.GetString("c9133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violação de acordo comercial.
        /// </summary>
        internal static string c9350 {
            get {
                return ResourceManager.GetString("c9350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao enviar a transação, tente novamente..
        /// </summary>
        internal static string c999 {
            get {
                return ResourceManager.GetString("c999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro não especificado.
        /// </summary>
        internal static string c9999 {
            get {
                return ResourceManager.GetString("c9999", resourceCulture);
            }
        }
    }
}
